// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtb0oJgDWMZudBcsZVuTS2McO1BQbMNss',
    appId: '1:1063459613275:web:c4d4ca6bb4d1b2a1cc6d7e',
    messagingSenderId: '1063459613275',
    projectId: 'ai-chat-fcae6',
    authDomain: 'ai-chat-fcae6.firebaseapp.com',
    storageBucket: 'ai-chat-fcae6.appspot.com',
    measurementId: 'G-SJEG1J95TZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkwWkB8lKKgdC1dZ217lDbg8EYjKn5Huw',
    appId: '1:1063459613275:android:a852985a26b5cf5ecc6d7e',
    messagingSenderId: '1063459613275',
    projectId: 'ai-chat-fcae6',
    storageBucket: 'ai-chat-fcae6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO4GLPIKSi5s4qdWZBzyt8Fo6j1ItBtAE',
    appId: '1:1063459613275:ios:4b3ec7b359325c6bcc6d7e',
    messagingSenderId: '1063459613275',
    projectId: 'ai-chat-fcae6',
    storageBucket: 'ai-chat-fcae6.appspot.com',
    iosBundleId: 'com.example.aiTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtb0oJgDWMZudBcsZVuTS2McO1BQbMNss',
    appId: '1:1063459613275:web:d336df9a1c1bce6fcc6d7e',
    messagingSenderId: '1063459613275',
    projectId: 'ai-chat-fcae6',
    authDomain: 'ai-chat-fcae6.firebaseapp.com',
    storageBucket: 'ai-chat-fcae6.appspot.com',
    measurementId: 'G-HPGFTT6RCS',
  );
}
